# Generated by Django 5.1.7 on 2025-07-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Shop/Products_images', verbose_name='Image')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nom du produit')),
                ('description', models.CharField(max_length=240, verbose_name='Description')),
                ('badge', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Top ventes', 'Top ventes'), ('Promo', 'Promo')], max_length=60, verbose_name='Badge')),
                ('price', models.IntegerField(verbose_name='Prix')),
                ('stock', models.IntegerField(verbose_name='En stock')),
                ('main_category', models.CharField(choices=[('Kits Arduino et IOT', 'Kits Arduino et IOT'), ('Machines Numeriques', 'Machines Numeriques'), ('Installations FabLab', 'Installations FabLab')], max_length=60, verbose_name='Categorie principale')),
                ('category', models.CharField(choices=[('Kits Arduino', 'Kits Arduino'), ('Composants IOT', 'Composants IOT'), ('Robotique', 'Robotique'), ('Capteurs', 'Capteurs')], max_length=60, verbose_name='Catégorie')),
                ('disponibility', models.CharField(choices=[('En stock', 'En stock'), ('Stock limité', 'Stock limité'), ('En rupture', 'En rupture')], max_length=60, verbose_name='Disponibilité')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
    ]
