# Generated by Django 5.1.7 on 2025-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('Nouveau', 'Nouveau'), ('Top ventes', 'Top ventes'), ('Promo', 'Promo')], max_length=60, null=True, verbose_name='Badge'),
        ),
    ]
