# Generated by Django 5.1.7 on 2025-07-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_product_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Kits Arduino et IOT', 'Kits Arduino et IOT'), ('Machines Numériques', 'Machines Numériques'), ('Installations Fablab', 'Installations Fablab')], max_length=60, verbose_name='Categorie principale'),
        ),
    ]
