# Generated by Django 5.1.7 on 2025-08-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_product_options_cart_complete_cart_status_and_more'),
        ('Users', '0003_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('total_amount', models.IntegerField(verbose_name='Montant total')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Facture PDF')),
                ('complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Finalisée')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Expédiée', 'Expédiée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée'), ('Remboursée', 'Remboursée')], default='En cours', max_length=20, verbose_name='État de la commande')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Users.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Prix')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='Shop.product')),
            ],
        ),
    ]
