# Generated by Django 5.1.7 on 2025-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_remove_cart_complete_remove_cart_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Frais de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Orange Money', 'Orange Money'), ('Wave', 'Wave')], max_length=50, null=True, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.ImageField(default='FabLab Product', upload_to='', verbose_name='Reference'),
            preserve_default=False,
        ),
    ]
