# Generated by Django 5.1.7 on 2025-08-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_remove_orderitem_price_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disponibility',
            field=models.CharField(choices=[('En stock', 'En stock'), ('Stock limité', 'Stock limité'), ('Rupture de stock', 'Rupture de stock')], max_length=60, verbose_name='Disponibilité'),
        ),
    ]
