# Generated by Django 5.1.7 on 2025-08-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_product_disponibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="URL de l'image"),
        ),
    ]
