# Generated by Django 5.1.7 on 2025-08-16 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_product_image_url'),
        ('Users', '0005_alter_client_adress_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.client'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Shop.product'),
        ),
    ]
