# Generated by Django 5.1.7 on 2025-08-16 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_cart_guest_orderitem_price_alter_cartitem_product'),
        ('Users', '0005_alter_client_adress_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.client'),
        ),
    ]
