# Generated by Django 5.1.7 on 2025-08-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Orange Money', 'Orange Money'), ('Wave', 'Wave')], default='Wave', max_length=50, null=True, verbose_name='Méthode de paiement'),
        ),
    ]
