# Generated by Django 5.1.7 on 2025-08-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_alter_order_payment_method'),
        ('Users', '0006_fab_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='Users.client'),
        ),
    ]
