# Generated by Django 5.1.7 on 2025-08-21 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_alter_cart_guest'),
        ('Users', '0006_fab_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_pdf',
        ),
        migrations.AlterField(
            model_name='addresschipping',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Users.client'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=100, verbose_name='Reference'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date_time', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0, verbose_name='Prix total')),
                ('last_updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Derniere modification')),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('invoice_type', models.CharField(choices=[('RECEIPT', 'RECEIPT'), ('PROFORMA INVOICE', 'PROFORMA INVOICE'), ('INVOICE', 'INVOICE')], max_length=60, verbose_name='Type de facture')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Facture PDF')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.client', verbose_name='Client')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shop.order', verbose_name='Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
