# Generated by Django 5.2.5 on 2025-08-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_remove_order_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date_time'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='guest',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date d’échéance'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ninea_number',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Numéro d’Identification Nationale des Entreprises et Associations'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rccm_number',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Numéro Registre de Commerce et du Crédit Mobilier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total HT'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TVA en pourcentage (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='api_response_id',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='id reponse CINETPAY'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Token de payment CINETPAY'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Url de payment CINETPAY'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro de suivi'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Merci pour votre confiance.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('RECEIPT', 'RECEIPT'), ('PROFORMA INVOICE', 'PROFORMA INVOICE'), ('INVOICE', 'INVOICE')], default='PROFORMA INVOICE', max_length=60, verbose_name='Type de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC'),
        ),
    ]
