# Generated by Django 5.2.5 on 2025-08-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_alter_invoice_options_remove_invoice_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Shop.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Shop.product'),
        ),
    ]
