# Generated by Django 5.2.5 on 2025-08-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_remove_cart_guest_remove_order_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_token',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='Token Session'),
        ),
    ]
