# Generated by Django 5.2.5 on 2025-08-28 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_cart_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='echeance_payment',
            field=models.IntegerField(default=7, verbose_name='Échéance de paiement en jour'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='Shop.order'),
        ),
    ]
