# Generated by Django 5.2.5 on 2025-08-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_order_echeance_payment_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='ninea_number',
            field=models.CharField(blank=True, default='Numéro d’Identification Nationale des Entreprises et Associations', max_length=160, null=True, verbose_name='Numéro d’Identification Nationale des Entreprises et Associations'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rccm_number',
            field=models.CharField(blank=True, default='Numéro Registre de Commerce et du Crédit Mobilier', max_length=160, null=True, verbose_name='Numéro Registre de Commerce et du Crédit Mobilier'),
        ),
    ]
