# Generated by Django 5.2.5 on 2025-08-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_alter_invoice_ninea_number_alter_invoice_rccm_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
