# Generated by Django 5.2.5 on 2025-09-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0023_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_token',
        ),
    ]
