# Generated by Django 5.2.5 on 2025-09-09 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0024_remove_cart_session_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='api_response_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_token',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='addresschipping',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('done', models.BooleanField(default=False, verbose_name='Payé')),
                ('payment_token', models.CharField(default='', max_length=500, unique=True, verbose_name='Token de payment CINETPAY')),
                ('payment_url', models.CharField(default='', max_length=500, unique=True, verbose_name='Url de payment CINETPAY')),
                ('api_response_id', models.CharField(default='', max_length=500, unique=True, verbose_name='id reponse CINETPAY')),
                ('payment_method', models.CharField(choices=[('orange', 'orange'), ('wave', 'wave')], max_length=50, verbose_name='Méthode de paiement')),
                ('total_amount', models.IntegerField(verbose_name='Montant total')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.order', verbose_name='Commande')),
            ],
        ),
    ]
