# Generated by Django 5.2.5 on 2025-09-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0025_remove_order_api_response_id_remove_order_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_url',
        ),
    ]
