# Generated by Django 5.2.5 on 2025-10-12 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0026_remove_payment_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Payée', 'Payée'), ('Remboursée', 'Remboursée')], default='En cours', max_length=20, verbose_name='État de la commande'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('orange', 'orange'), ('wave', 'wave')], default='orange', max_length=50, verbose_name='Méthode de paiement'),
        ),
    ]
