# Generated by Django 5.2.5 on 2025-10-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0028_alter_invoice_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payée'),
        ),
    ]
