# Generated by Django 5.2.5 on 2025-12-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fab_user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur'),
        ),
        migrations.AddField(
            model_name='fab_user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Compte banni'),
        ),
    ]
