# Generated by Django 5.2.5 on 2025-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_fab_user_is_admin_fab_user_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fab_user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Compte actif'),
        ),
        migrations.AlterField(
            model_name='fab_user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='fab_user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super utilisateur'),
        ),
    ]
