# Generated by Django 5.1.7 on 2025-07-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fab_user',
            name='status',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client')], default='Client', max_length=20, verbose_name='Statut'),
            preserve_default=False,
        ),
    ]
