# Generated by Django 5.1.7 on 2025-07-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_fab_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fab_user',
            name='picture_profile',
        ),
    ]
