# Generated by Django 5.1.7 on 2025-08-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_client_delete_invoice_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
