# Generated by Django 5.1.7 on 2025-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
