# Generated by Django 5.1.7 on 2025-08-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_client_adress_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fab_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
