# Generated by Django 5.2.5 on 2025-11-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Activité')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'activité")),
                ('description_accueil', models.TextField(blank=True, null=True, verbose_name="Description courte pour l'accueil")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('presentation_img', models.ImageField(blank=True, null=True, upload_to='activity_images/', verbose_name='Image accueil')),
                ('motiv1', models.TextField(blank=True, null=True, verbose_name='Motivation 1')),
                ('motiv2', models.TextField(blank=True, null=True, verbose_name='Motivation 2')),
                ('url_name', models.CharField(max_length=50, unique=True, verbose_name="Nom de l'URL")),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGalerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity_galerie/', verbose_name='Image de la galerie')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'image")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'image")),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_images', to='Activities.activity', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Images de la galerie',
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Éducation Numérique', 'Éducation Numérique'), ('Projets Innovants', 'Projets Innovants'), ('Impact Communautaire', 'Impact Communautaire')], max_length=50, verbose_name="Catégorie de l'impact")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'impact")),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='Activities.activity', verbose_name='Activité')),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la réalisation')),
                ('category', models.CharField(choices=[('Ateliers Réguliers', 'Ateliers Réguliers'), ('Compétitions', 'Compétitions'), ('FabLabs Équipés', 'FabLabs Équipés')], max_length=50, verbose_name='Catégorie de la réalisation')),
                ('stat1', models.IntegerField(blank=True, null=True, verbose_name='Statistique 1')),
                ('stat2', models.IntegerField(blank=True, null=True, verbose_name='Statistique 2')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='Activities.activity', verbose_name='Activité')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du résultat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resultat_images/', verbose_name='Image du résultat')),
                ('stat1', models.IntegerField(blank=True, null=True, verbose_name='Statistique 1')),
                ('stat2', models.IntegerField(blank=True, null=True, verbose_name='Statistique 2')),
                ('stat3', models.IntegerField(blank=True, null=True, verbose_name='Statistique 3')),
                ('stat4', models.IntegerField(blank=True, null=True, verbose_name='Statistique 4')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='Activities.activity', verbose_name='Activité')),
            ],
        ),
    ]
