# Generated by Django 5.2.5 on 2025-12-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impact',
            options={'verbose_name': 'Notre Impact', 'verbose_name_plural': 'Notre Impact'},
        ),
        migrations.AlterModelOptions(
            name='realisation',
            options={'verbose_name': 'Nos Réalisations', 'verbose_name_plural': 'Nos Réalisations'},
        ),
        migrations.AlterModelOptions(
            name='resultat',
            options={'verbose_name': 'Résultats Concrets', 'verbose_name_plural': 'Résultats Concrets'},
        ),
    ]
