# Generated by Django 5.2.5 on 2025-12-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
    ]
