"""
Django settings for AntaBackEnd project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')
CINETPAY_API_KEY = config("CINETPAY_API_KEY")
CINETPAY_SITE_ID = config("CINETPAY_SITE_ID")
CINETPAY_SECRET_KEY = config("CINETPAY_SECRET_KEY")


 
# SECURITY WARNING: don't run with debug turned on in production!
LOCAL = os.getenv("LOCAL", "False") == "True"
DEBUG = os.getenv("DEBUG", "False") == "True"

print(f"DEBUG: {DEBUG}, LOCAL: {LOCAL}")

if DEBUG:
    DOMAIN_NAME = 'http://127.0.0.1:8001'
else:
    DOMAIN_NAME = 'https://projet-site-linguere.onrender.com'

ALLOWED_HOSTS = [
    '.onrender.com',  
    'linguerefablab.com',               
    'www.linguerefablab.com',
    "projet-site-linguere.onrender.com",
    "localhost",
    "172.31.124.218",
    "127.0.0.1",
    ]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('SMTP_SERVER')
EMAIL_PORT = config('SMTP_PORT')
EMAIL_HOST_USER = config('SENDER')
EMAIL_HOST_PASSWORD = config('PASSWORD') 
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'Activities.apps.ActivitiesConfig',
    'Formations.apps.FormationsConfig',
    'New_features.apps.NewFeaturesConfig',
    'Partners.apps.PartnersConfig',
    'Services.apps.ServicesConfig',
    'Shop.apps.ShopConfig',
    'Testimonies.apps.TestimoniesConfig',
    'Personalizations.apps.PersonalizationsConfig',
    'Users.apps.UsersConfig',
    'django_extensions',
    'colorfield',
    'admin_extra_buttons',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AntaBackEnd.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "AntaBackEnd" / "templates", BASE_DIR / "Activities" / "templates",
                 BASE_DIR / "Shop" / "templates", BASE_DIR / "Users" / "templates", BASE_DIR / "Services" / "templates",
                 BASE_DIR / "Formations" / "templates", BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Shop.context_processors.get_cart_data',
                'Users.context_processors.get_user_id',
            ],
        },
    },
]

ASGI_APPLICATION = 'AntaBackEnd.asgi.application'
WSGI_APPLICATION = 'AntaBackEnd.wsgi.application'

if not DEBUG and not LOCAL:
    # Mode production
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [config('CELERY_BROKER_URL', default='redis://localhost:6379/0')],
            },
        },
    }

elif LOCAL:
    # Mode local (sans redis)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

else:
    # Mode debug, mais avec Redis
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [config('CELERY_BROKER_URL', default='redis://localhost:6379/0')],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('LOCAL_DB_NAME'),
            'USER': config('LOCAL_DB_USER'),
            'PASSWORD': config('LOCAL_DB_PASSWORD'),
            'HOST': config('LOCAL_DB_HOST'),
            'PORT': config('LOCAL_DB_PORT'),
        }
    }
else:
    DATABASES = {
    'default': dj_database_url.config(
        # Replace this value with your local database's connection string.
        default=config('DATABASE_URL'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Media files
MEDIA_URL = 'media/' if LOCAL else '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/' if LOCAL else '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "AntaBackEnd" / "static", BASE_DIR / "static"]

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG and not LOCAL:

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

if DEBUG:
    MIDDLEWARE.remove('whitenoise.middleware.WhiteNoiseMiddleware')


LOGIN_REDIRECT_URL = "home"

LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = LOGIN_URL

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "Users.Fab_User"

# configuring Django messages framework
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Email configuration
EMAIL_HOST = config('SMTP_SERVER')
EMAIL_PORT = config('SMTP_PORT', cast=int)
EMAIL_HOST_USER = config('SENDER')
EMAIL_HOST_PASSWORD = config('PASSWORD')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'Linguere FabLab <linguerefablab.net@gmail.com>'

# Celery

if LOCAL:
    CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
    CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
else:
    CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')


CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Réduire la concurrence sous WSL2
CELERY_WORKER_CONCURRENCY = 2  # au lieu de 8

# Recycler les workers pour éviter les fuites mémoire
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

# Reconnexion automatique au démarrage
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Tentatives de reconnexion (None = infini)
CELERY_BROKER_CONNECTION_MAX_RETRIES = None

# Timeout de transport
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'socket_timeout': 30,
    'socket_connect_timeout': 30,
    'retry_on_timeout': True,
}

# Activer si vous êtes bien en production (DEBUG = False)
if not DEBUG:
    # Indique à Django de faire passer les cookies de session uniquement via HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Indique à Django que Render agit comme un proxy HTTPS inversé
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # ÉVITE LE BLOCAGE DES FORMULAIRES (Ajout de vos domaines sécurisés)
    CSRF_TRUSTED_ORIGINS = [
        'https://linguerefablab.com',        
        'https://www.linguerefablab.com',    
        'https://projet-site-linguere.onrender.com', 
    ]