# Generated by Django 5.2.13 on 2026-05-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('description_accueil', models.TextField(default='Pas de description sur accueil', help_text="Cette description s'affichera sur la page d'accueil", verbose_name='Description accueil')),
                ('description', models.TextField(default='Pas de description', verbose_name='Description')),
                ('slug', models.SlugField(blank=True, default='', max_length=128, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalerieImageForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Services/galerie_image/default3.png', upload_to='Services/galerie_image', verbose_name='Image')),
                ('service', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galerie_images', to='Services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Image de la galerie pour service',
                'verbose_name_plural': 'Images de la galerie pour services',
            },
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Identifiant unique sans espaces ni accents (ex: support_type)', max_length=100, verbose_name='Nom technique')),
                ('label', models.CharField(help_text="Ce que l'utilisateur verra (ex: Type de support)", max_length=150, verbose_name='Label affiché')),
                ('field_type', models.CharField(choices=[('text', 'Texte libre'), ('integer', 'Nombre entier'), ('select', 'Liste déroulante (choix unique)'), ('multicolor', 'Sélecteur de couleurs (choix multiple)'), ('file', 'Fichier / Image'), ('boolean', 'Case à cocher (Oui/Non)')], max_length=20, verbose_name='Type de champ')),
                ('required', models.BooleanField(default=True, verbose_name='Obligatoire ?')),
                ('choices', models.JSONField(blank=True, help_text='Liste des choix au format JSON. Ex: ["Option1", "Option2"]', null=True, verbose_name='Options (pour liste déroulante)')),
                ('has_other', models.BooleanField(default=False, verbose_name='A une option "Autre (Préciser)" ?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Champ de service',
                'verbose_name_plural': 'Champs de service',
                'ordering': ['service', 'order'],
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largeur (en cm)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Hauteur (en cm)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Instructions spéciales')),
                ('delivery_mode', models.CharField(blank=True, choices=[('Retrait sur place (Dakar)', 'Retrait sur place (Dakar)'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=180, verbose_name='Mode de livraison')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Services/orders/', verbose_name='Fichier / Image')),
                ('img_path', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Chemin de l'image")),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone du client')),
                ('client_address', models.CharField(blank=True, max_length=255, verbose_name='Adresse du client')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', verbose_name='Valeur')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='Services.servicefield', verbose_name='Champ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='Services.serviceorder', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Valeur de champ de commande',
                'verbose_name_plural': 'Valeurs de champs de commande',
            },
        ),
    ]
