# Generated by Django 5.2.5 on 2026-01-04 18:11

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesWithColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Chemin de l'image")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Instructions Spéciales')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('width', models.IntegerField(verbose_name='Largeur (en cm)')),
                ('height', models.IntegerField(verbose_name='Hauteur (en cm)')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone du client')),
                ('client_address', models.CharField(blank=True, max_length=255, verbose_name='Adresse du client')),
                ('delivery_mode', models.CharField(blank=True, choices=[('Retrait sur place (Dakar)', 'Retrait sur place (Dakar)'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=180, verbose_name='Mode de livraison')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecoupeLaserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Chemin de l'image")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Instructions Spéciales')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('width', models.IntegerField(verbose_name='Largeur (en cm)')),
                ('height', models.IntegerField(verbose_name='Hauteur (en cm)')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone du client')),
                ('client_address', models.CharField(blank=True, max_length=255, verbose_name='Adresse du client')),
                ('delivery_mode', models.CharField(blank=True, choices=[('Retrait sur place (Dakar)', 'Retrait sur place (Dakar)'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=180, verbose_name='Mode de livraison')),
                ('image', models.ImageField(blank=True, upload_to='Services/DecoupeLaser', verbose_name='Image à découper')),
                ('service_type', models.CharField(choices=[('Découpe', 'Découpe'), ('Gravure', 'Gravure')], max_length=100, verbose_name='Type de service')),
                ('used_material', models.CharField(choices=[('Bois', 'Bois'), ('Acrylic', 'Acrylic'), ('Cuir', 'Cuir'), ('Métal', 'Métal')], max_length=100, verbose_name='Matériau utilisé')),
            ],
            options={
                'verbose_name': 'Commande pour Découpe Laser',
                'verbose_name_plural': 'Commandes pour Découpe Laser',
            },
        ),
        migrations.CreateModel(
            name='FraiseCNCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Chemin de l'image")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Instructions Spéciales')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('width', models.IntegerField(verbose_name='Largeur (en cm)')),
                ('height', models.IntegerField(verbose_name='Hauteur (en cm)')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone du client')),
                ('client_address', models.CharField(blank=True, max_length=255, verbose_name='Adresse du client')),
                ('delivery_mode', models.CharField(blank=True, choices=[('Retrait sur place (Dakar)', 'Retrait sur place (Dakar)'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=180, verbose_name='Mode de livraison')),
                ('image', models.ImageField(blank=True, upload_to='Services/FraiseCNC', verbose_name='Image à fraiser')),
                ('service_type', models.CharField(choices=[('Découpe', 'Découpe'), ('Gravure', 'Gravure')], max_length=100, verbose_name='Type de service')),
                ('used_material', models.CharField(choices=[('Bois', 'Bois'), ('Aluminium', 'Aluminium'), ('PVC', 'PVC')], max_length=100, verbose_name='Matériau utilisé')),
            ],
            options={
                'verbose_name': 'Commande pour Fraise CNC',
                'verbose_name_plural': 'Commandes pour Fraise CNC',
            },
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('description_accueil', models.TextField(default='Pas de description sur accueil', help_text="Cette description s'affichera sur la page d'acueil", verbose_name='Description accueil')),
                ('description', models.TextField(default='Pas de description', verbose_name='Description')),
                ('slug', models.SlugField(blank=True, default='', max_length=128, verbose_name='Slug')),
                ('impressionNumerique', models.BooleanField(default=False, verbose_name="Service d'impression numérique ?")),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BroderieNumeriqueModel',
            fields=[
                ('serviceswithcolors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Services.serviceswithcolors')),
                ('image', models.ImageField(blank=True, upload_to='Services/BroderieNumerique', verbose_name='Image à broder')),
                ('support_type', models.CharField(choices=[('T-shirt', 'T-shirt'), ('Casquette', 'Casquette'), ('Laoste', 'Laoste'), ('Polo', 'Polo'), ('Sweat à capuche', 'Sweat à capuche'), ('Serviette', 'Serviette'), ('Sac', 'Sac'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=100, verbose_name='Type de support')),
                ('other_support', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre support (si applicable)')),
            ],
            options={
                'verbose_name': 'Commande pour broderie Numérique',
                'verbose_name_plural': 'Commandes pour broderie Numérique',
            },
            bases=('Services.serviceswithcolors',),
        ),
        migrations.CreateModel(
            name='Impression3DModel',
            fields=[
                ('serviceswithcolors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Services.serviceswithcolors')),
                ('image', models.ImageField(blank=True, upload_to='Services/Impression3D', verbose_name='Image à imprimer')),
                ('impression_type', models.CharField(choices=[('FDM(Plastique)', 'FDM(Plastique)'), ('SLA(Résine)', 'SLA(Résine)'), ('SLS(Poudre)', 'SLS(Poudre)')], max_length=100, verbose_name="Type d'impression")),
                ('used_material', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('RESINE', 'RESINE')], max_length=100, verbose_name='Matériau utilisé')),
            ],
            options={
                'verbose_name': 'Commande pour Impression 3D',
                'verbose_name_plural': 'Commandes pour Impression 3D',
            },
            bases=('Services.serviceswithcolors',),
        ),
        migrations.CreateModel(
            name='ImpressionObjPersonnaliseModel',
            fields=[
                ('serviceswithcolors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Services.serviceswithcolors')),
                ('image', models.ImageField(blank=True, upload_to='Services/ImpressionObjPersonnalise', verbose_name='Image à imprimer')),
                ('obj_type', models.CharField(choices=[('T-shirt', 'T-shirt'), ('Casquette', 'Casquette'), ('Laoste', 'Laoste'), ('Polo', 'Polo'), ('Sweat à capuche', 'Sweat à capuche'), ('Serviette', 'Serviette'), ('Sac', 'Sac'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=100, verbose_name="Type d'objet")),
                ('other_object', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre objet (si applicable)')),
                ('design_file', models.CharField(choices=[('PNG', 'PNG'), ('AI', 'AI'), ('PSD', 'PSD'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=50, verbose_name='Fichier de design')),
                ('other_file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre fichier (si applicable)')),
            ],
            options={
                'verbose_name': 'Commande pour Impression Objet Personnalisé',
                'verbose_name_plural': 'Commandes pour Impression Objet Personnalisé',
            },
            bases=('Services.serviceswithcolors',),
        ),
        migrations.CreateModel(
            name='ImpressionPaperSupportRigideModel',
            fields=[
                ('serviceswithcolors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Services.serviceswithcolors')),
                ('image', models.ImageField(blank=True, upload_to='Services/ImpressionPaperSupportRigide', verbose_name='Image à imprimer')),
                ('format', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=100, verbose_name='Format souhaité')),
                ('other_format', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre format (si applicable)')),
                ('paper_type', models.CharField(choices=[('mat', 'mat'), ('brillant', 'brillant'), ('recyclé', 'recyclé'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=100, verbose_name='Type de papier')),
                ('other_paper', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre papier (si applicable)')),
                ('design_file', models.CharField(choices=[('PNG', 'PNG'), ('AI', 'AI'), ('PSD', 'PSD'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=50, verbose_name='Fichier de design')),
                ('other_file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre fichier (si applicable)')),
            ],
            options={
                'verbose_name': 'Commande pour Impression Papier/Support Rigide',
                'verbose_name_plural': 'Commandes pour Impression Papier/Support Rigide',
            },
            bases=('Services.serviceswithcolors',),
        ),
        migrations.CreateModel(
            name='ImpressionTextileEtVetementModel',
            fields=[
                ('serviceswithcolors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Services.serviceswithcolors')),
                ('image', models.ImageField(blank=True, upload_to='Services/ImpressionTextileEtVetement', verbose_name='Image à imprimer')),
                ('textile_type', models.CharField(choices=[('Coton', 'Coton'), ('Polyester', 'Polyester'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=100, verbose_name='Type de textile')),
                ('other_textile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre textile (si applicable)')),
                ('impression_type', models.CharField(choices=[('Sérigraphie', 'Sérigraphie'), ('Sublimation', 'Sublimation'), ('Impression', 'Impression'), ('Direct', 'Direct')], max_length=100, verbose_name="Type d'impression")),
                ('design_file', models.CharField(choices=[('PNG', 'PNG'), ('AI', 'AI'), ('PSD', 'PSD'), ('Autre (Préciser)', 'Autre (Préciser)')], max_length=50, verbose_name='Fichier de design')),
                ('other_design_file', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autre fichier (si applicable)')),
            ],
            options={
                'verbose_name': 'Commande pour Impression Textile et Vêtement',
                'verbose_name_plural': 'Commandes pour Impression Textile et Vêtement',
            },
            bases=('Services.serviceswithcolors',),
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(choices=[('#000000', 'black'), ('#ff0000', 'red'), ('#0000ff', 'blue'), ('#ffffff', 'white'), ('#ffc0cb', 'pink'), ('#5e35b1', 'purple'), ('#32cd32', 'green'), ('#ffa500', 'orange'), ('#ffd700', 'yellow'), ('#c0c0c0', 'silver')], default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Couleur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_colors', to='Services.serviceswithcolors')),
            ],
            options={
                'verbose_name': 'Couleur pour Service',
                'verbose_name_plural': 'Couleurs pour Service',
            },
        ),
        migrations.CreateModel(
            name='GalerieImageForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Services/galerie_image/default3.png', upload_to='Services/galerie_image', verbose_name='Image')),
                ('service', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galerie_images', to='Services.serviceinfo', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Image de la galerie pour service',
                'verbose_name_plural': 'Images de la galerie pour services',
            },
        ),
    ]
