# Generated by Django 5.2.5 on 2025-11-18 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_picture', models.ImageField(blank=True, null=True, upload_to='Services/user_imported_imgs', verbose_name='Image importée')),
                ('chosen_picture', models.URLField(blank=True, null=True, verbose_name='Image choisie')),
                ('adress_delivery', models.CharField(choices=[('Retrait sur place (Dakar)', 'Retrait sur place (Dakar)'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], verbose_name='Adresse de livraison')),
                ('delivery_mode', models.CharField(max_length=180, verbose_name='Mode de livraison')),
                ('fields_value', models.JSONField(default=dict)),
                ('cgu_accept', models.BooleanField(default=False, verbose_name='Accepter les conditions de confidentialité')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la commande')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='FieldForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_field', models.TextField(help_text="Si c'est un champ groupé, les names des inputs doivent être différents et être comme [first_nom_champ, last_nom_champ]", verbose_name='Code Html des Champs')),
                ('grouped', models.BooleanField(default=False, help_text='Le champ est-il groupé ? (plusieurs inputs pour un même champ)', verbose_name='Champs groupé ?')),
                ('header_icon_class', models.CharField(help_text="Classe de l'icône du header (ex: fa-solid fa-user)", max_length=64, verbose_name='class du header')),
                ('header_icon_txt', models.CharField(default='', help_text='Texte du header (ex: Instructions spéciales)', max_length=64, verbose_name='Texte du header')),
                ('is_support_field', models.BooleanField(default=False, verbose_name='Champs de support ?')),
            ],
            options={
                'verbose_name': 'Champ pour service personnalisé',
                'verbose_name_plural': 'Champs pour services personnalisés',
            },
        ),
        migrations.CreateModel(
            name='GalerieImageForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Services/galerie_image/default3.png', upload_to='Services/galerie_image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image de la galerie pour service',
                'verbose_name_plural': 'Images de la galerie pour services',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('description_accueil', models.TextField(default='Pas de description sur accueil', help_text="Cette description s'affichera sur la page d'acueil", verbose_name='Description accueil')),
                ('description', models.TextField(default='Pas de description', verbose_name='Description')),
                ('slug', models.SlugField(blank=True, default='', max_length=128, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
    ]
