# Generated by Django 5.2.13 on 2026-05-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('integer', 'Nombre entier'), ('select', 'Liste déroulante (choix unique)'), ('multicolor', 'Sélecteur de couleurs (choix multiple)'), ('file', 'Fichier / Image'), ('file_path', 'Image de la galerie (stocke le chemin)'), ('boolean', 'Case à cocher (Oui/Non)')], max_length=20, verbose_name='Type de champ'),
        ),
    ]
