# Generated by Django 5.2.5 on 2026-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='class_icon_name',
            field=models.CharField(default='', help_text="Classe de l'icône du service (ex: fa-solid fa-tshirt)", max_length=30, verbose_name="class de l'icône"),
        ),
        migrations.AlterField(
            model_name='impression3dmodel',
            name='impression_type',
            field=models.CharField(choices=[('PLA(Plastique)', 'PLA(Plastique)'), ('SLA(Résine)', 'SLA(Résine)'), ('SLS(Poudre)', 'SLS(Poudre)')], max_length=100, verbose_name="Type d'impression"),
        ),
    ]
