# Generated by Django 5.2.13 on 2026-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_servicefield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefield',
            name='name',
            field=models.SlugField(editable=False, help_text='Identifiant unique sans espaces ni accents (ex: support_type)', max_length=100, verbose_name='Nom technique'),
        ),
    ]
