# Generated by Django 5.2.13 on 2026-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_servicefield_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefield',
            name='choices',
            field=models.JSONField(blank=True, help_text='Liste des choix au format JSON. Ex: ["Option1", "Option2"]', null=True, verbose_name='Options (pour liste déroulante) / Liste de couleurs (pour multicolor)'),
        ),
    ]
