# Generated by Django 5.2.13 on 2026-05-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_servicefield_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicefield',
            options={'ordering': ['service', 'order'], 'verbose_name': 'Champ de personnalisation', 'verbose_name_plural': 'Champs de personnalisation'},
        ),
    ]
