# Generated by Django 5.2.13 on 2026-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_alter_servicefield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('integer', 'Nombre entier'), ('select', 'Liste déroulante (choix unique)'), ('multicolor', 'Sélecteur de couleurs (choix multiple)'), ('boolean', 'Case à cocher (Oui/Non)')], max_length=20, verbose_name='Type de champ'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Services/orders/', verbose_name='Image uploadée'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='img_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Chemin de l'image sélectionnée dans la galerie"),
        ),
    ]
