# Generated by Django 5.2.5 on 2025-11-17 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressChipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date_time', models.DateTimeField(auto_now_add=True)),
                ('rccm_number', models.CharField(blank=True, default='Numéro Registre de Commerce et du Crédit Mobilier', max_length=160, null=True, verbose_name='Numéro Registre de Commerce et du Crédit Mobilier')),
                ('ninea_number', models.CharField(blank=True, default='Numéro d’Identification Nationale des Entreprises et Associations', max_length=160, null=True, verbose_name='Numéro d’Identification Nationale des Entreprises et Associations')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date d’échéance')),
                ('last_updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total HT')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TVA en pourcentage (%)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('paid', models.BooleanField(default=False, verbose_name='Payée')),
                ('invoice_type', models.CharField(choices=[('RECEIPT', 'RECEIPT'), ('PROFORMA INVOICE', 'PROFORMA INVOICE'), ('INVOICE', 'INVOICE')], default='PROFORMA INVOICE', max_length=60, verbose_name='Type de facture')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Merci pour votre confiance.')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Facture PDF')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-invoice_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Finalisée')),
                ('echeance_payment', models.IntegerField(default=7, verbose_name='Échéance de paiement en jour')),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro de suivi')),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Payée', 'Payée'), ('Remboursée', 'Remboursée')], default='En cours', max_length=20, verbose_name='État de la commande')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='Frais de livraison')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('done', models.BooleanField(default=False, verbose_name='Payé')),
                ('payment_token', models.CharField(default='', max_length=500, unique=True, verbose_name='Token de payment CINETPAY')),
                ('api_response_id', models.CharField(default='', max_length=500, unique=True, verbose_name='id reponse CINETPAY')),
                ('payment_method', models.CharField(choices=[('orange', 'orange'), ('wave', 'wave')], default='orange', max_length=50, verbose_name='Méthode de paiement')),
                ('total_amount', models.IntegerField(verbose_name='Montant total')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('image', models.ImageField(upload_to='Shop/Products_images', verbose_name='Image')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nom du produit')),
                ('description', models.CharField(max_length=240, verbose_name='Description')),
                ('badge', models.CharField(blank=True, choices=[('Nouveau', 'Nouveau'), ('Top ventes', 'Top ventes'), ('Promo', 'Promo')], max_length=60, null=True, verbose_name='Badge')),
                ('price', models.IntegerField(verbose_name='Prix')),
                ('stock', models.IntegerField(verbose_name='En stock')),
                ('main_category', models.CharField(choices=[('Kits Arduino et IOT', 'Kits Arduino et IOT'), ('Machines Numériques', 'Machines Numériques'), ('Installations Fablab', 'Installations Fablab')], max_length=60, verbose_name='Categorie principale')),
                ('category', models.CharField(choices=[('Kits Arduino', 'Kits Arduino'), ('Composants IOT', 'Composants IOT'), ('Robotique', 'Robotique'), ('Capteurs', 'Capteurs')], max_length=60, verbose_name='Catégorie')),
                ('disponibility', models.CharField(choices=[('En stock', 'En stock'), ('Stock limité', 'Stock limité'), ('Rupture de stock', 'Rupture de stock')], max_length=60, verbose_name='Disponibilité')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('image_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="URL de l'image")),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['-added_date'],
            },
        ),
    ]
