# Generated by Django 5.2.13 on 2026-05-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Kits Arduino', 'Kits Arduino'), ('Composants IoT', 'Composants IoT'), ('Robotique', 'Robotique'), ('Capteurs', 'Capteurs')], max_length=60, null=True, verbose_name='Catégorie'),
        ),
    ]
