# Generated by Django 5.1.7 on 2025-05-14 14:13

import Services.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 5')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 6')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 7')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 8')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCustomizationForBroderieNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Type de support')),
                ('dim_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 1')),
                ('dim_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 2')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('design_picture', models.CharField(blank=True, max_length=60, null=True, verbose_name='Image du design')),
                ('upload_design_picture', models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'dst'], message='Seuls les fichiers PNG, JPG, JPEG, SVG et DST sont autorisés.')], verbose_name='Design uploadé')),
                ('codeCouleur', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code couleur')),
                ('name', models.CharField(max_length=30, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=50, verbose_name='Adresse mail')),
                ('tel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de téléphone')),
                ('town', models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresse (ville)')),
                ('delivery_mode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de livraison')),
                ('cgu_accept', models.BooleanField(default=False, verbose_name='Accepter les conditions de confidentialité')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.service', verbose_name='Service')),
            ],
        ),
    ]
