# Generated by Django 5.1.7 on 2025-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nom'),
        ),
    ]
