# Generated by Django 5.1.7 on 2025-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image4',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image5',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image6',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image7',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 7'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image8',
            field=models.ImageField(blank=True, default='Services/service_image/default3.png', null=True, upload_to='Services/service_image', verbose_name='Image 8'),
        ),
    ]
