# Generated by Django 5.1.7 on 2025-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_service_image1_alter_service_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomizationforbroderienumerique',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=50, null=True, verbose_name='Mode de livraison'),
        ),
    ]
