# Generated by Django 5.1.7 on 2025-05-15 15:18

import Services.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_clientcustomizationforfraiseusenumerique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCustomizationForDecoupeLaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Type de service')),
                ('dim_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 1')),
                ('dim_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 2')),
                ('used_materials', models.CharField(blank=True, max_length=30, null=True, verbose_name='Matériau utilisé')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('design_picture', models.CharField(blank=True, max_length=60, null=True, verbose_name='Image du design')),
                ('upload_design_picture', models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'dst'], message='Seuls les fichiers PNG, JPG, JPEG, SVG et DST sont autorisés.')], verbose_name='Design uploadé')),
                ('name', models.CharField(max_length=30, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=50, verbose_name='Adresse mail')),
                ('tel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de téléphone')),
                ('town', models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresse (ville)')),
                ('delivery_mode', models.CharField(blank=True, choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=50, null=True, verbose_name='Mode de livraison')),
                ('cgu_accept', models.BooleanField(default=False, verbose_name='Accepter les conditions de confidentialité')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.service')),
            ],
        ),
    ]
