# Generated by Django 5.2.5 on 2025-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='header_text',
        ),
        migrations.AddField(
            model_name='activity',
            name='url_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name="Nom de l'URL"),
            preserve_default=False,
        ),
    ]
