# Generated by Django 5.2.5 on 2025-09-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_remove_impact_header_text_activity_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitygalerieimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'image"),
        ),
        migrations.AddField(
            model_name='activitygalerieimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'image"),
        ),
    ]
