# Generated by Django 5.2.5 on 2025-09-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_activitygalerieimage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
    ]
