# Generated by Django 5.2.5 on 2025-09-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_accueil',
            field=models.TextField(blank=True, null=True, verbose_name="Description courte pour l'accueil"),
        ),
    ]
