# Generated by Django 5.2.5 on 2025-09-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_activity_description_accueil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitygalerieimage',
            options={'verbose_name': 'Images de la galerie'},
        ),
    ]
