# Generated by Django 5.1.7 on 2025-04-26 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('duration', models.DurationField()),
                ('motiv', models.TextField()),
                ('price', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('availability', models.CharField(choices=[('online', 'En ligne'), ('in person', 'En présentiel'), ('both', 'Hybride')], max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('1', 'Débutant'), ('2', 'Amateur'), ('3', 'Expert')], max_length=15)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
        ),
        migrations.CreateModel(
            name='SignedUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.CharField(max_length=20)),
                ('formation_method', models.CharField(choices=[('en-ligne', 'En ligne'), ('presentiel', 'En présentiel'), ('hybride', 'Hybride')], default='en-ligne', max_length=30)),
                ('session', models.CharField(choices=[('matin', 'Matin (9h-12h)'), ('apres-midi', 'Après-midi (14h-17h)'), ('soir', 'Soir (18h-21h)')], default='matin', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
        ),
        migrations.CreateModel(
            name='SkillGained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
        ),
        migrations.CreateModel(
            name='UserBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('en-ligne', 'En ligne'), ('presentiel', 'En présentiel'), ('hybride', 'Hybride')], default='en-ligne', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
        ),
    ]
