# Generated by Django 5.1.7 on 2025-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='availability',
            field=models.CharField(choices=[('online', 'En ligne'), ('in person', 'En présentiel'), ('both', 'Hybride')], default='both', max_length=30),
        ),
        migrations.AlterField(
            model_name='formations',
            name='hours_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formations',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='formations',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
