# Generated by Django 5.1.7 on 2025-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0002_alter_formations_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='availability',
            field=models.CharField(blank=True, choices=[('online', 'En ligne'), ('in person', 'En présentiel'), ('both', 'Hybride')], default='both', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formations',
            name='hours_per_week',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
