# Generated by Django 5.1.7 on 2025-04-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0003_alter_formations_availability_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formations',
            options={'verbose_name': 'Formation'},
        ),
    ]
