# Generated by Django 5.1.7 on 2025-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0004_alter_formations_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
