# Generated by Django 5.1.7 on 2025-04-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0005_alter_formations_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signedupuser',
            options={'verbose_name': 'Personnes Inscrites'},
        ),
    ]
