# Generated by Django 5.1.7 on 2025-04-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0006_alter_signedupuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbrochure',
            options={'verbose_name': 'Utilisateurs ayant demandé brochure'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'Utilisateurs ayant demandé écrit'},
        ),
    ]
