# Generated by Django 5.1.7 on 2025-04-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0008_alter_userrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'verbose_name': 'Préréquis par formation'},
        ),
        migrations.AlterModelOptions(
            name='skillgained',
            options={'verbose_name': 'Compétences acquise par formations'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': 'Témoignages'},
        ),
    ]
