# Generated by Django 5.1.7 on 2025-04-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0010_alter_signedupuser_options_alter_skillgained_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'Utilisateurs ayant pris renseignement'},
        ),
    ]
