# Generated by Django 5.1.7 on 2025-04-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0011_alter_userrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'Utilisateurs ayant prit renseignement'},
        ),
    ]
