# Generated by Django 5.1.7 on 2025-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0012_alter_userrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrochure',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
