# Generated by Django 5.1.7 on 2025-04-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0013_userbrochure_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillgained',
            name='description',
        ),
        migrations.AlterField(
            model_name='formations',
            name='availability',
            field=models.CharField(blank=True, choices=[('online', 'En ligne'), ('in person', 'En présentiel'), ('both', 'Hybride')], default='both', max_length=30, null=True, verbose_name='Disponibilité'),
        ),
        migrations.AlterField(
            model_name='formations',
            name='duration',
            field=models.DurationField(verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='formations',
            name='hours_per_week',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'heures par semaines"),
        ),
        migrations.AlterField(
            model_name='formations',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='formations',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom du module'),
        ),
        migrations.AlterField(
            model_name='signedupuser',
            name='formation_method',
            field=models.CharField(choices=[('en-ligne', 'En ligne'), ('presentiel', 'En présentiel'), ('hybride', 'Hybride')], default='en-ligne', max_length=30, verbose_name='Méthode de formation'),
        ),
        migrations.AlterField(
            model_name='signedupuser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='signedupuser',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='comment',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='username',
            field=models.CharField(max_length=30, verbose_name="Nom d'utiisateur"),
        ),
        migrations.AlterField(
            model_name='userbrochure',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations', verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='userbrochure',
            name='method',
            field=models.CharField(choices=[('en-ligne', 'En ligne'), ('presentiel', 'En présentiel'), ('hybride', 'Hybride')], default='en-ligne', max_length=20, verbose_name='Méthode de formation'),
        ),
        migrations.AlterField(
            model_name='userbrochure',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userbrochure',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations', verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
