# Generated by Django 5.1.7 on 2025-04-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0014_remove_skillgained_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='determinant',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='formations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image descriptive de la formation'),
        ),
        migrations.AddField(
            model_name='prerequisites',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Formations/prerequis_image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='formations',
            name='availability',
            field=models.CharField(blank=True, choices=[('online', 'En ligne'), ('in person', 'En présentiel'), ('both', 'En ligne / Présentiel')], default='both', max_length=30, null=True, verbose_name='Disponibilité'),
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Avantages de nos formations',
            },
        ),
        migrations.CreateModel(
            name='MotivPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Motivations',
            },
        ),
    ]
