# Generated by Django 5.1.7 on 2025-04-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0017_alter_formations_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='availability',
            field=models.CharField(blank=True, choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne / Présentiel', max_length=30, null=True, verbose_name='Disponibilité'),
        ),
    ]
