# Generated by Django 5.1.7 on 2025-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0019_alter_advantages_options_alter_formations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivpoints',
            options={'ordering': ['name'], 'verbose_name': 'Motivation'},
        ),
        migrations.RemoveField(
            model_name='signedupuser',
            name='formation_method',
        ),
        migrations.RemoveField(
            model_name='userbrochure',
            name='method',
        ),
        migrations.AddField(
            model_name='signedupuser',
            name='availability',
            field=models.CharField(choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne / Présentiel', max_length=30, verbose_name='Disponibilité'),
        ),
        migrations.AddField(
            model_name='userbrochure',
            name='availability',
            field=models.CharField(choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne', max_length=22, verbose_name='Méthode de formation'),
        ),
        migrations.AlterField(
            model_name='signedupuser',
            name='session',
            field=models.CharField(choices=[('Matin (9h-12h)', 'Matin (9h-12h)'), ('Après-midi (14h-17h)', 'Après-midi (14h-17h)'), ('Soir (18h-21h)', 'Soir (18h-21h)')], default='Matin (9h-12h)', max_length=30),
        ),
    ]
