# Generated by Django 5.1.7 on 2025-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0020_alter_motivpoints_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisites',
            name='level',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Amateur', 'Amateur'), ('Expert', 'Expert')], max_length=15),
        ),
    ]
