# Generated by Django 5.1.7 on 2025-07-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('duration', models.DurationField(verbose_name='Durée')),
                ('motiv', models.TextField()),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Prix')),
                ('hours_per_week', models.IntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'heures par semaines")),
                ('availability', models.CharField(blank=True, choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne / Présentiel', max_length=30, null=True, verbose_name='Disponibilité')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('determinant', models.CharField(default='', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image descriptive de la formation')),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillGained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description_skill', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Compétences acquise par formation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Statut')),
                ('comment', models.TextField(verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Témoignage',
            },
        ),
        migrations.CreateModel(
            name='UserBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne', max_length=22, verbose_name='Méthode de formation')),
            ],
            options={
                'verbose_name': 'Utilisateurs ayant demandé brochure',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Utilisateurs ayant prit renseignement',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Avantages de nos formations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom du module')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Modules des formations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MotivPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Motivation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('Débutant', 'Débutant'), ('Amateur', 'Amateur'), ('Expert', 'Expert')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Formations/prerequis_image', verbose_name='Image')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Préréquis par formation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignedUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne / Présentiel', max_length=30, verbose_name='Disponibilité')),
                ('session', models.CharField(choices=[('Matin (9h-12h)', 'Matin (9h-12h)'), ('Après-midi (14h-17h)', 'Après-midi (14h-17h)'), ('Soir (18h-21h)', 'Soir (18h-21h)')], default='Matin (9h-12h)', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Personnes Inscrite',
            },
        ),
    ]
