# Generated by Django 5.1.7 on 2025-07-11 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signedupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillgained',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbrochure',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='userbrochure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
