# Generated by Django 5.2.5 on 2025-09-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='description_accueil',
            field=models.TextField(default='', verbose_name='Description sur page accueil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formations',
            name='url_name',
            field=models.CharField(default='', max_length=120, verbose_name="Nom de l'url"),
            preserve_default=False,
        ),
    ]
