# Generated by Django 5.2.5 on 2025-09-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0003_formations_description_accueil_formations_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formations',
            name='determinant',
        ),
        migrations.AddField(
            model_name='formations',
            name='image_home',
            field=models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image de la formation sur page accueil'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advantages', to='Formations.formations'),
        ),
        migrations.AlterField(
            model_name='module',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modules', to='Formations.formations'),
        ),
        migrations.AlterField(
            model_name='motivpoints',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MotivPoints', to='Formations.formations'),
        ),
        migrations.AlterField(
            model_name='prerequisites',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prerequisites', to='Formations.formations'),
        ),
        migrations.AlterField(
            model_name='signedupuser',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SignedUpUsers', to='Formations.formations'),
        ),
        migrations.AlterField(
            model_name='skillgained',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SkillsGained', to='Formations.formations'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonies', to='Formations.formations'),
        ),
        migrations.AlterField(
            model_name='userbrochure',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserBrochures', to='Formations.formations', verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRequest', to='Formations.formations', verbose_name='Formation'),
        ),
    ]
