# Generated by Django 5.2.5 on 2025-09-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0004_remove_formations_determinant_formations_image_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom du module'),
        ),
    ]
