# Generated by Django 5.2.5 on 2025-09-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0005_alter_module_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': 'Module de formation', 'verbose_name_plural': 'Modules des formations'},
        ),
    ]
