# Generated by Django 5.2.5 on 2025-09-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0006_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='why_image',
            field=models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image qui motive'),
        ),
    ]
