# Generated by Django 5.2.5 on 2025-09-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0007_formations_why_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantages',
            options={'ordering': ['name'], 'verbose_name': 'Avantage de notre formation', 'verbose_name_plural': 'Pourquoi Choisir Notre Formation ?'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': 'Module de formation', 'verbose_name_plural': 'Modules principaux'},
        ),
        migrations.AlterModelOptions(
            name='motivpoints',
            options={'ordering': ['name'], 'verbose_name': 'Motivation', 'verbose_name_plural': 'Pourquoi suivre cette formation ?'},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'ordering': ['name'], 'verbose_name': 'Préréquis par formation', 'verbose_name_plural': 'Maîtrise les Technologies & Compétences Essentielles'},
        ),
        migrations.AlterModelOptions(
            name='skillgained',
            options={'ordering': ['name'], 'verbose_name': 'Compétences acquise par formation', 'verbose_name_plural': 'Ce Que Vous Allez Acquérir'},
        ),
    ]
