# Generated by Django 5.2.5 on 2025-09-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0008_alter_advantages_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
