# Generated by Django 5.1.7 on 2025-04-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0009_alter_prerequisites_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signedupuser',
            options={'verbose_name': 'Personnes Inscrite'},
        ),
        migrations.AlterModelOptions(
            name='skillgained',
            options={'verbose_name': 'Compétences acquise par formation'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': 'Témoignage'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'Utilisateurs ayant pri renseignement'},
        ),
    ]
