# Generated by Django 5.2.5 on 2025-09-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0009_delete_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formations',
            name='motiv',
        ),
    ]
