# Generated by Django 5.2.5 on 2025-09-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0010_remove_formations_motiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='why_image',
            field=models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image Pourquoi cette formation ?'),
        ),
    ]
