# Generated by Django 5.2.5 on 2025-10-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0011_alter_formations_why_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbrochure',
            options={'verbose_name': 'Demandes de brochures'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'Demandes de renseignements'},
        ),
    ]
