# Generated by Django 5.1.7 on 2025-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0015_formations_determinant_formations_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgained',
            name='description_skill',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
