# Generated by Django 5.1.7 on 2025-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0016_skillgained_description_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='availability',
            field=models.CharField(blank=True, choices=[('En ligne', 'online'), ('En présentiel', 'in person'), ('En ligne / Présentiel', 'both')], default='En ligne / Présentiel', max_length=30, null=True, verbose_name='Disponibilité'),
        ),
    ]
