# Generated by Django 5.1.7 on 2025-04-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0018_alter_formations_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantages',
            options={'ordering': ['name'], 'verbose_name': 'Avantages de nos formations'},
        ),
        migrations.AlterModelOptions(
            name='formations',
            options={'ordering': ['name'], 'verbose_name': 'Formation'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': 'Modules des formations'},
        ),
        migrations.AlterModelOptions(
            name='motivpoints',
            options={'ordering': ['name'], 'verbose_name': 'Motivations'},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'ordering': ['name'], 'verbose_name': 'Préréquis par formation'},
        ),
        migrations.AlterModelOptions(
            name='signedupuser',
            options={'ordering': ['name'], 'verbose_name': 'Personnes Inscrite'},
        ),
        migrations.AlterModelOptions(
            name='skillgained',
            options={'ordering': ['name'], 'verbose_name': 'Compétences acquise par formation'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['username'], 'verbose_name': 'Témoignage'},
        ),
        migrations.AlterModelOptions(
            name='userbrochure',
            options={'ordering': ['name'], 'verbose_name': 'Utilisateurs ayant demandé brochure'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ['name'], 'verbose_name': 'Utilisateurs ayant prit renseignement'},
        ),
    ]
