# Generated by Django 5.2.13 on 2026-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom du client')),
                ('testimony', models.TextField(verbose_name='Son témoignage')),
                ('picture', models.ImageField(upload_to='testimonies_pictures/', verbose_name='Sa photo')),
                ('user_short_description', models.CharField(max_length=30, verbose_name='Courte Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
