# Generated by Django 5.1.7 on 2025-05-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 4')),
            ],
        ),
    ]
