# Generated by Django 5.1.7 on 2025-05-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Adresse mail')),
                ('tel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de téléphone')),
                ('town', models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresse (ville)')),
                ('delivery_mode', models.CharField(blank=True, choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=50, null=True, verbose_name='Mode de livraison')),
                ('cgu_accept', models.BooleanField(default=False, verbose_name='Accepter les conditions de confidentialité')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Services/service_image', verbose_name='Image 4')),
                ('support_type', models.CharField(blank=True, choices=[('T-shirt', 'T-shirt'), ('Laoste', 'Laoste'), ('Casquette', 'Casquette'), ('Polo', 'Polo'), ('Sweat a capuche', 'Sweat a capuche'), ('Serviette', 'Serviette'), ('Sac', 'Sac'), ('Autre (précisez)', 'Autre (précisez)')], max_length=30, null=True, verbose_name='Type de support')),
                ('dim_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 1')),
                ('dim_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 2')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('other_support', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de support(Personnalisé)')),
            ],
        ),
        migrations.CreateModel(
            name='ColorForDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.service')),
            ],
        ),
    ]
