# Generated by Django 5.1.7 on 2025-05-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorForDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomizedServices',
        ),
        migrations.AddField(
            model_name='commande',
            name='cgu_accept',
            field=models.BooleanField(default=False, verbose_name='Accepter les conditions de confidentialité'),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], max_length=50, null=True, verbose_name='Mode de livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Adresse mail'),
        ),
        migrations.AddField(
            model_name='commande',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='commande',
            name='tel_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='commande',
            name='town',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresse (ville)'),
        ),
        migrations.AddField(
            model_name='service',
            name='dim_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='dim_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimension 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='other_support',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de support(Personnalisé)'),
        ),
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='service',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='support_type',
            field=models.CharField(blank=True, choices=[('T-shirt', 'T-shirt'), ('Laoste', 'Laoste'), ('Casquette', 'Casquette'), ('Polo', 'Polo'), ('Sweat a capuche', 'Sweat a capuche'), ('Serviette', 'Serviette'), ('Sac', 'Sac'), ('Autre (précisez)', 'Autre (précisez)')], max_length=30, null=True, verbose_name='Type de support'),
        ),
        migrations.AddField(
            model_name='colorfordesign',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.service'),
        ),
    ]
