# Generated by Django 5.1.7 on 2025-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='design_picture',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Image du design'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='design_picture',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Image du design'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='design_picture',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Image du design'),
        ),
    ]
