# Generated by Django 5.2.5 on 2025-09-20 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_accueil',
            field=models.TextField(default='', verbose_name='Description accueil'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GalerieImageForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Services/galerie_image/default3.png', upload_to='Services/galerie_image', verbose_name='Image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_images', to='Services.service', verbose_name='Service')),
            ],
        ),
    ]
