# Generated by Django 5.1.7 on 2025-06-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_clientcustomizationforobjects_design_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomizationforbroderienumerique',
            name='codeCouleur',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Code couleur'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='codeCouleur',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Code couleur'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='codeCouleur',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Code couleur'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='codeCouleur',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Code couleur'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='codeCouleur',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Code couleur'),
        ),
    ]
