# Generated by Django 5.2.5 on 2025-09-22 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_service_description_accueil_galerieimageforservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldForCustomizedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Commentaire', 'Commentaire'), ('Entier', 'Entier'), ("Liste d'entiers", "Liste d'entiers"), ('Liste de caractères', 'Liste de caractères')], max_length=80, verbose_name='Type de champ')),
                ('field_name', models.CharField(max_length=60, verbose_name='Type de champ')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image8',
        ),
        migrations.AddField(
            model_name='galerieimageforservice',
            name='fields_value',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='service',
            name='fields_set',
            field=models.JSONField(default={}),
        ),
        migrations.CreateModel(
            name='CustomizedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_picture', models.ImageField(blank=True, null=True, upload_to='Services/user_imported_imgs', verbose_name='Image importée')),
                ('adress_delivery', models.CharField(max_length=180, verbose_name='Adresse de livraison')),
                ('delivery_mode', models.CharField(max_length=180, verbose_name='Mode de livraison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
