# Generated by Django 5.1.7 on 2025-06-24 13:07

import Services.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_clientcustomizationforbroderienumerique_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomizationforbroderienumerique',
            name='codeCouleur',
            field=models.CharField(default='#010101', max_length=80, verbose_name='Code couleur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforbroderienumerique',
            name='delivery_mode',
            field=models.CharField(choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], default='Retrait sur place Dakar', max_length=50, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforbroderienumerique',
            name='special_instructions',
            field=models.TextField(default='s', verbose_name='Instructions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforbroderienumerique',
            name='support_type',
            field=models.CharField(choices=[('T-shirt', 'T-shirt'), ('Casquette', 'Casquette'), ('Laoste', 'Laoste'), ('Polo', 'Polo'), ('Sweat à capuche', 'Sweat à capuche'), ('Serviette', 'Serviette'), ('Sac', 'Sac'), ('Autre (précisez)', 'Autre (précisez)')], default='T-shirt', max_length=30, verbose_name='Type de support'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='delivery_mode',
            field=models.CharField(choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], default='Retrait sur place Dakar', max_length=50, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='dim_1',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='dim_2',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='service_type',
            field=models.CharField(choices=[('Découpe', 'Découpe'), ('Gravure', 'Gravure')], default='Découpe', max_length=30, verbose_name='Type de service'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='special_instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='tel_number',
            field=models.CharField(default='', max_length=50, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='town',
            field=models.CharField(default='', max_length=60, verbose_name='Adresse (ville)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='upload_design_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'dxf', 'ai'], message='Seuls les fichiers SVG, DXF, AI sont autorisés.')], verbose_name='Design uploadé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfordecoupelaser',
            name='used_materials',
            field=models.CharField(choices=[('Acrylique', 'Acrylique'), ('Bois', 'Bois'), ('Métal', 'Métal'), ('Cuir', 'Cuir')], default='Acrylique', max_length=30, verbose_name='Matériau utilisé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='delivery_mode',
            field=models.CharField(choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], default='Retrait sur place Dakar', max_length=50, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='service_type',
            field=models.CharField(choices=[('Découpe', 'Découpe'), ('Gravure', 'Gravure')], default='Découpe', max_length=30, verbose_name='Type de service'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='special_instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='upload_design_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'dxf', 'ai'], message='Seuls les fichiers STL, DXF, AI sont autorisés.')], verbose_name='Design uploadé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='used_materials',
            field=models.CharField(choices=[('Bois', 'Bois'), ('Aluminium', 'Aluminium'), ('PVC', 'PVC')], default='Bois', max_length=30, verbose_name='Matériau utilisé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='codeCouleur',
            field=models.CharField(default='', max_length=80, verbose_name='Code couleur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='delivery_mode',
            field=models.CharField(choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], default='Retrait sur place Dakar', max_length=50, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='dim_1',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='dim_2',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='impression_type',
            field=models.CharField(choices=[('FDM(Plastique)', 'FDM(Plastique)'), ('SLA(Résine)', 'SLA(Résine)'), ('SLS(Poudre)', 'SLS(Poudre)')], default='FDM(Plastique)', max_length=30, verbose_name="Type d'impression"),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='special_instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='tel_number',
            field=models.CharField(default='', max_length=50, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='town',
            field=models.CharField(default='', max_length=60, verbose_name='Adresse (ville)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='upload_design_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj'], message='Seuls les fichiers STL, OBJ sont autorisés.')], verbose_name='Design uploadé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforimpression3d',
            name='used_materials',
            field=models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('Résine', 'Résine')], default='PLA', max_length=30, verbose_name='Matériau utilisé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='codeCouleur',
            field=models.CharField(default='', max_length=80, verbose_name='Code couleur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='delivery_mode',
            field=models.CharField(choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], default='Retrait sur place Dakar', max_length=50, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='design_file',
            field=models.CharField(choices=[('AI', 'AI'), ('PNG', 'PNG'), ('PSD', 'PSD'), ('Autre (précisez)', 'Autre (précisez)')], default='AI', max_length=30, verbose_name='Fichier du design'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='dim_1',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='dim_2',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='object',
            field=models.CharField(choices=[('T-shirt', 'T-shirt'), ('Casquette', 'Casquette'), ('Laoste', 'Laoste'), ('Polo', 'Polo'), ('Sweat à capuche', 'Sweat à capuche'), ('Serviette', 'Serviette'), ('Sac', 'Sac'), ('Autre (précisez)', 'Autre (précisez)')], default='T-shirt', max_length=30, verbose_name="Type de d'objet"),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='special_instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='tel_number',
            field=models.CharField(default='', max_length=50, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='town',
            field=models.CharField(default='', max_length=60, verbose_name='Adresse (ville)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforobjects',
            name='upload_design_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj'], message='Seuls les fichiers STL, OBJ sont autorisés.')], verbose_name='Design uploadé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='codeCouleur',
            field=models.CharField(default='', max_length=80, verbose_name='Code couleur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='delivery_mode',
            field=models.CharField(choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], default='Retrait sur place Dakar', max_length=50, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='design_file',
            field=models.CharField(choices=[('AI', 'AI'), ('PNG', 'PNG'), ('PSD', 'PSD'), ('Autre (précisez)', 'Autre (précisez)')], default='AI', max_length=30, verbose_name='Fichier du design'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='dim_1',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='dim_2',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='paper',
            field=models.CharField(choices=[('Mat', 'Mat'), ('Brillant', 'Brillant'), ('Recyclé', 'Recyclé'), ('Autre (précisez)', 'Autre (précisez)')], default='Mat', max_length=60, null=True, verbose_name='Type de papier'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='special_instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='tel_number',
            field=models.CharField(default='', max_length=50, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='town',
            field=models.CharField(default='', max_length=60, verbose_name='Adresse (ville)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='upload_design_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj'], message='Seuls les fichiers STL, OBJ sont autorisés.')], verbose_name='Design uploadé'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='wished_format',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A5', 'A5'), ('Autre (précisez)', 'Autre (précisez)')], default='A4', max_length=30, verbose_name='Format souhaité'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='codeCouleur',
            field=models.CharField(default='', max_length=80, verbose_name='Code couleur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='delivery_mode',
            field=models.CharField(choices=[('Retrait sur place Dakar', 'Retrait sur place Dakar'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], default='Retrait sur place Dakar', max_length=50, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='design_file',
            field=models.CharField(choices=[('AI', 'AI'), ('PNG', 'PNG'), ('PSD', 'PSD'), ('Autre (précisez)', 'Autre (précisez)')], default='AI', max_length=30, verbose_name='Fichier du design'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='dim_1',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='dim_2',
            field=models.CharField(default=0, max_length=30, verbose_name='Dimension 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='impression_wished',
            field=models.CharField(choices=[('Serigraphie', 'Sérigraphie'), ('Impression', 'Impression'), ('Sublimation', 'Sublimation'), ('Directe', 'Directe')], default='Serigraphie', max_length=60, null=True, verbose_name="Type d'impression souhaité"),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='special_instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='tel_number',
            field=models.CharField(default='', max_length=50, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='textile_type',
            field=models.CharField(choices=[('Coton', 'Coton'), ('Polyester', 'Polyester'), ('Autre (précisez)', 'Autre (précisez)')], default='Coton', max_length=30, verbose_name='Type de textile'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='town',
            field=models.CharField(default='', max_length=60, verbose_name='Adresse (ville)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='upload_design_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj'], message='Seuls les fichiers STL, OBJ sont autorisés.')], verbose_name='Design uploadé'),
        ),
    ]
