# Generated by Django 5.2.5 on 2025-09-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_fieldforcustomizedservice_remove_service_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerieimageforservice',
            name='fields_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='service',
            name='fields_set',
            field=models.JSONField(default=dict),
        ),
    ]
