# Generated by Django 5.2.5 on 2025-09-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_galerieimageforservice_fields_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_field', models.TextField(max_length=256, verbose_name='Code Html du Champ')),
            ],
        ),
        migrations.DeleteModel(
            name='FieldForCustomizedService',
        ),
        migrations.RemoveField(
            model_name='galerieimageforservice',
            name='fields_value',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fields_set',
        ),
        migrations.AddField(
            model_name='customizedservice',
            name='fields_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customizedservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_services', to='Services.service'),
        ),
        migrations.AddField(
            model_name='fieldforservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='html_fields', to='Services.service'),
        ),
    ]
