# Generated by Django 5.1.7 on 2025-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_clientcustomizationforbroderienumerique_codecouleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomizationforbroderienumerique',
            name='codeCouleur',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Code couleur'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationforpaper',
            name='paper',
            field=models.CharField(choices=[('Mat', 'Mat'), ('Brillant', 'Brillant'), ('Recyclé', 'Recyclé'), ('Autre (précisez)', 'Autre (précisez)')], default='Mat', max_length=60, verbose_name='Type de papier'),
        ),
        migrations.AlterField(
            model_name='clientcustomizationfortextile',
            name='impression_wished',
            field=models.CharField(choices=[('Serigraphie', 'Sérigraphie'), ('Impression', 'Impression'), ('Sublimation', 'Sublimation'), ('Directe', 'Directe')], default='Serigraphie', max_length=60, verbose_name="Type d'impression souhaité"),
        ),
    ]
