# Generated by Django 5.1.7 on 2025-07-01 20:05

import Services.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_alter_clientcustomizationforbroderienumerique_codecouleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='upload_design_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Services/uploaded_design', validators=[Services.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'dst'], message='Seuls les fichiers PNG, JPG, JPEG, SVG et DST sont autorisés.')], verbose_name='Design uploadé'),
        ),
    ]
