# Generated by Django 5.2.5 on 2025-09-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_fieldforservice_delete_fieldforcustomizedservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=128, verbose_name='Slug'),
        ),
    ]
