# Generated by Django 5.2.5 on 2025-09-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedservice',
            name='adress_delivery',
            field=models.CharField(choices=[('Retrait sur place (Dakar)', 'Retrait sur place (Dakar)'), ('Livraison à domicile (Dakar)', 'Livraison à domicile (Dakar)'), ('Livraison à domicile (Autres régions)', 'Livraison à domicile (Autres régions)')], verbose_name='Adresse de livraison'),
        ),
    ]
