# Generated by Django 5.2.5 on 2025-09-23 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_alter_customizedservice_adress_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedservice',
            name='cgu_accept',
            field=models.BooleanField(default=False, verbose_name='Accepter les conditions de confidentialité'),
        ),
        migrations.AddField(
            model_name='customizedservice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la commande'),
        ),
    ]
