# Generated by Django 5.2.5 on 2025-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_customizedservice_cgu_accept_customizedservice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Slug'),
        ),
    ]
