# Generated by Django 5.2.5 on 2025-09-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=128, verbose_name='Slug'),
        ),
    ]
