# Generated by Django 5.2.5 on 2025-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldforservice',
            name='html_field',
            field=models.TextField(max_length=256, verbose_name='Code Html des Champs'),
        ),
    ]
