# Generated by Django 5.2.5 on 2025-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_alter_fieldforservice_html_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldforservice',
            name='html_field',
            field=models.TextField(verbose_name='Code Html des Champs'),
        ),
    ]
