# Generated by Django 5.2.5 on 2025-09-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_alter_fieldforservice_html_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedservice',
            name='chosen_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Image choisie'),
        ),
    ]
