# Generated by Django 5.2.5 on 2025-09-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0014_customizedservice_chosen_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldforservice',
            name='grouped',
            field=models.BooleanField(default=False, verbose_name='Champs groupé ?'),
        ),
    ]
