# Generated by Django 5.2.5 on 2025-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_fieldforservice_grouped'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldforservice',
            name='header_icon_class',
            field=models.CharField(default='', max_length=64, verbose_name='class du header'),
            preserve_default=False,
        ),
    ]
