# Generated by Django 5.2.5 on 2025-09-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_fieldforservice_header_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldforservice',
            name='header_icon_txt',
            field=models.CharField(default='', max_length=64, verbose_name='Texte du header'),
        ),
    ]
