# Generated by Django 5.2.5 on 2025-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_fieldforservice_header_icon_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldforservice',
            name='grouped',
            field=models.BooleanField(default=False, help_text='Le champ est-il groupé ? (plusieurs inputs pour un même champ)', verbose_name='Champs groupé ?'),
        ),
        migrations.AlterField(
            model_name='fieldforservice',
            name='header_icon_class',
            field=models.CharField(help_text="Classe de l'icône du header (ex: fa-solid fa-user)", max_length=64, verbose_name='class du header'),
        ),
        migrations.AlterField(
            model_name='fieldforservice',
            name='header_icon_txt',
            field=models.CharField(default='', help_text='Texte du header (ex: Instructions spéciales)', max_length=64, verbose_name='Texte du header'),
        ),
        migrations.AlterField(
            model_name='fieldforservice',
            name='html_field',
            field=models.TextField(help_text="Si c'est un champ groupé, les names des inputs doivent être différents et être comme [first_nom_champ, last_nom_champ]", verbose_name='Code Html des Champs'),
        ),
    ]
