# Generated by Django 5.2.5 on 2025-10-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_alter_fieldforservice_grouped_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldforservice',
            options={'verbose_name': 'Champ pour service personnalisé', 'verbose_name_plural': 'Champs pour services personnalisés'},
        ),
    ]
