# Generated by Django 5.2.5 on 2025-10-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_alter_fieldforservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerieimageforservice',
            options={'verbose_name': 'Image de la galerie pour service', 'verbose_name_plural': 'Images de la galerie pour services'},
        ),
    ]
