# Generated by Django 5.2.5 on 2025-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0020_alter_galerieimageforservice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='Pas de description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_accueil',
            field=models.TextField(default='Pas de description sur accueil', verbose_name='Description accueil'),
        ),
    ]
