# Generated by Django 5.2.5 on 2025-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0021_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_accueil',
            field=models.TextField(default='Pas de description sur accueil', help_text="Cette description s'affichera sur la page d'acueil", verbose_name='Description accueil'),
        ),
    ]
