# Generated by Django 5.2.5 on 2025-10-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0022_alter_service_description_accueil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128, verbose_name='Slug'),
        ),
    ]
