# Generated by Django 5.2.5 on 2025-10-08 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0023_alter_service_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcustomizationfordecoupelaser',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationfordecoupelaser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforfraiseusenumerique',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforimpression3d',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforimpression3d',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforobjects',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforobjects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforpaper',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationforpaper',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationfortextile',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clientcustomizationfortextile',
            name='user',
        ),
        migrations.AlterField(
            model_name='customizedservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galerieimageforservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galerie_images', to='Services.service', verbose_name='Service'),
        ),
        migrations.DeleteModel(
            name='ClientCustomizationForBroderieNumerique',
        ),
        migrations.DeleteModel(
            name='ClientCustomizationForDecoupeLaser',
        ),
        migrations.DeleteModel(
            name='ClientCustomizationForFraiseuseNumerique',
        ),
        migrations.DeleteModel(
            name='ClientCustomizationForImpression3D',
        ),
        migrations.DeleteModel(
            name='ClientCustomizationForObjects',
        ),
        migrations.DeleteModel(
            name='ClientCustomizationForPaper',
        ),
        migrations.DeleteModel(
            name='ClientCustomizationForTextile',
        ),
    ]
