# Generated by Django 5.2.5 on 2025-10-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0024_remove_clientcustomizationfordecoupelaser_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldforservice',
            name='is_support_field',
            field=models.BooleanField(default=False, verbose_name='Champs de support ?'),
        ),
    ]
