# Generated by Django 5.2.5 on 2025-10-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0025_fieldforservice_is_support_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizedservice',
            options={'verbose_name': 'Service personnalisé', 'verbose_name_plural': 'Services personnalisés'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
