# Generated by Django 5.2.5 on 2025-10-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0026_alter_customizedservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizedservice',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
    ]
