# Generated by Django 5.2.13 on 2026-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesOnHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='homepage_images/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='homepage_images/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='homepage_images/', verbose_name='Image 3')),
            ],
            options={
                'verbose_name': 'Personalization',
                'verbose_name_plural': 'Personalizations',
            },
        ),
    ]
