# Generated by Django 5.2.5 on 2025-12-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank='False', upload_to='Features/')),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
