# Generated by Django 5.2.5 on 2025-12-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
        ),
    ]
