# Generated by Django 5.2.5 on 2025-11-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('duration', models.DurationField(verbose_name='Durée')),
                ('description_accueil', models.TextField(verbose_name='Description sur page accueil')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Prix')),
                ('hours_per_week', models.IntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'heures par semaines")),
                ('availability', models.CharField(blank=True, choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne / Présentiel', max_length=30, null=True, verbose_name='Disponibilité')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image descriptive de la formation')),
                ('url_name', models.CharField(max_length=120, verbose_name="Nom de l'url")),
                ('image_home', models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image de la formation sur page accueil')),
                ('why_image', models.ImageField(blank=True, null=True, upload_to='Formations/formation_image', verbose_name='Image Pourquoi cette formation ?')),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillGained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description_skill', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Compétences acquise par formation',
                'verbose_name_plural': 'Ce Que Vous Allez Acquérir',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne', max_length=22, verbose_name='Méthode de formation')),
            ],
            options={
                'verbose_name': 'Demandes de brochures',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Demandes de renseignements',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advantages', to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Avantage de notre formation',
                'verbose_name_plural': 'Pourquoi Choisir Notre Formation ?',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du module')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modules', to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Module de formation',
                'verbose_name_plural': 'Modules principaux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MotivPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MotivPoints', to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Motivation',
                'verbose_name_plural': 'Pourquoi suivre cette formation ?',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('Débutant', 'Débutant'), ('Amateur', 'Amateur'), ('Expert', 'Expert')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Formations/prerequis_image', verbose_name='Image')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prerequisites', to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Préréquis par formation',
                'verbose_name_plural': 'Maîtrise les Technologies & Compétences Essentielles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignedUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('En ligne', 'En ligne'), ('En présentiel', 'En présentiel'), ('En ligne / Présentiel', 'En ligne / Présentiel')], default='En ligne / Présentiel', max_length=30, verbose_name='Disponibilité')),
                ('session', models.CharField(choices=[('Matin (9h-12h)', 'Matin (9h-12h)'), ('Après-midi (14h-17h)', 'Après-midi (14h-17h)'), ('Soir (18h-21h)', 'Soir (18h-21h)')], default='Matin (9h-12h)', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SignedUpUsers', to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Personnes Inscrite',
            },
        ),
    ]
