# Generated by Django 5.2.13 on 2026-05-01 00:32
from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0002_initial'),
    ]

    operations = [
    migrations.AddField(
        model_name='formations',
        name='brochure',
        field=models.FileField(
            upload_to='Formations/brochures',
            null=True,
            blank=True
        ),
    ),
]
