# Generated by Django 5.2.5 on 2026-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nom'),
        ),
    ]
