# Generated by Django 5.2.5 on 2025-12-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': 'Modules principaux', 'verbose_name_plural': 'Modules principaux'},
        ),
        migrations.AlterModelOptions(
            name='motivpoints',
            options={'ordering': ['name'], 'verbose_name': 'Pourquoi Apprendre la Broderie Numérique ?', 'verbose_name_plural': 'Pourquoi Apprendre la Broderie Numérique ?'},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'ordering': ['name'], 'verbose_name': 'Maîtrise les Technologies & Compétences Essentielles', 'verbose_name_plural': 'Maîtrise les Technologies & Compétences Essentielles'},
        ),
        migrations.AlterModelOptions(
            name='skillgained',
            options={'ordering': ['name'], 'verbose_name': 'Ce Que Vous Allez Acquérir', 'verbose_name_plural': 'Ce Que Vous Allez Acquérir'},
        ),
    ]
