# Generated by Django 5.2.5 on 2025-12-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formations',
            options={'ordering': ['name'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='motivpoints',
            options={'ordering': ['name'], 'verbose_name': 'Motivation', 'verbose_name_plural': 'Motivations'},
        ),
        migrations.AlterField(
            model_name='advantages',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='motivpoints',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='motivpoints',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='prerequisites',
            name='level',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Amateur', 'Amateur'), ('Expert', 'Expert')], max_length=15, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='prerequisites',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='signedupuser',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='signedupuser',
            name='session',
            field=models.CharField(choices=[('Matin (9h-12h)', 'Matin (9h-12h)'), ('Après-midi (14h-17h)', 'Après-midi (14h-17h)'), ('Soir (18h-21h)', 'Soir (18h-21h)')], default='Matin (9h-12h)', max_length=30, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='skillgained',
            name='description_skill',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skillgained',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userbrochure',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
