# Generated by Django 5.2.13 on 2026-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0003_auto_20260501_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='Formations/brochures', verbose_name='Brochure de la formation'),
        ),
    ]
