# Generated by Django 5.2.5 on 2025-12-08 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0003_alter_module_options_alter_motivpoints_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formations')),
            ],
            options={
                'verbose_name': 'Questions Fréquemment Posées',
                'verbose_name_plural': 'Questions Fréquemment Posées',
            },
        ),
    ]
