# Generated by Django 5.2.5 on 2026-02-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0003_alter_formations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='formations',
            name='duration',
            field=models.DurationField(help_text='Doit être au format Nb_Jours hh:mm:ss', verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='motivpoints',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='prerequisites',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='skillgained',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nom'),
        ),
    ]
