# Generated by Django 5.2.13 on 2026-05-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0004_alter_formations_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='name_in_fomation_page',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nom de la formation sur la page de formation'),
        ),
    ]
