# Generated by Django 5.2.13 on 2026-05-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0005_formations_name_in_fomation_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formations',
            old_name='name_in_fomation_page',
            new_name='name_in_formation_page',
        ),
    ]
