# Generated by Django 5.2.13 on 2026-05-13 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0006_rename_name_in_fomation_page_formations_name_in_formation_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquestions',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AskedQuestions', to='Formations.formations'),
        ),
    ]
